spring:
  application:
    name: eureka-server
  boot:
    admin:
      context-path: /admin              
server:
  port: 8070
eureka:
  instance:
    hostname: eureka-server           
    prefer-ip-address: true           
  client:
    register-with-eureka: false       
    fetch-registry: false
    service-url:                      
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 5  
management:
  endpoints:
    web:
      exposure:
        include: "*"

